#redis做消息队列测试demo
spring:
  application:
    name=demo-redis:
  redis:
    host: 192.168.37.50
    port: 6379
    password: ipanel
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 30000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
    timeout: 6000ms # 连接超时时间（毫秒）
    database: 1 # Redis数据库索引（默认为0）

  #哨兵
#redis.sentinel.master=
#哨兵的配置列表
#redis.sentinel.nodes=
redis:
  channel: channel
  lpush:
    key: lpushList
    tmp:
      key: lpushTempList
